---
version: '3.6'

x-besu-bootnode-def:
  &besu-bootnode-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      /opt/besu/bin/besu public-key export --to=/tmp/bootnode_pubkey;
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/nodekey \
      --min-gas-price=0 \
      --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;


x-besu-def:
  &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |

      while [ ! -f "/opt/besu/public-keys/bootnode_pubkey" ]; do sleep 5; done ;
      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/nodekey \
      --min-gas-price=0 \
      --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;

x-besu-tx-def:
  &besu-tx-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  environment:
    - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
  entrypoint:
    - /bin/bash
    - -c
    - |


      for i in $$(seq 1 100)
      do
        set -e
        if [ "I'm up!" == "$$(wget --timeout 10 -qO- --proxy off 172.16.239.2$${NODE_ID}:9000/upcheck)" ];
          then break
        else
          echo "Waiting for Tessera..."
          sleep 10
        fi
      done



      while [ ! -f "/opt/besu/public-keys/bootnode_pubkey" ]; do sleep 5; done ;

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/nodekey \
      --min-gas-price=0 \
      --rpc-http-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;

x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: quorumengineering/quorum:${QUORUM_VERSION:-latest}
  expose:
    - 30303
    - 8545
    - 9545
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      export CONSENSUS_ARGS="--istanbul.blockperiod 5 --mine --minerthreads 1 --miner.gasprice 0 --emitcheckpoints"
      export QUORUM_API="istanbul,qbft"

      mkdir -p /config /data /var/log/quorum/;
      cp /quorum/passwords.txt /config/passwords.txt
      cp -r /quorum/* /data;
      geth --datadir=/data init /config/genesis.json;
      cp /config/keys/accountkey /data/keystore/key;
      cp /config/keys/nodekey /data/geth/nodekey;
      geth \
      --datadir /data \
      --nodiscover \
      --permissioned \
      --verbosity 5 \
      $$CONSENSUS_ARGS \
      --syncmode full --nousb \
      --metrics --pprof --pprofaddr 0.0.0.0 --pprofport 9545 \
      --networkid $${QUORUM_NETWORK_ID:-1337} \
      --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcvhosts "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,$$QUORUM_API \
      --port 30303 \
      --identity node$${NODE_ID}-$${GOQUORUM_CONS_ALGO} \
      --unlock 0 \
      --allow-insecure-unlock \
      --password /config/passwords.txt \
      &> /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log | tee -a /var/log/quorum/geth-$$HOSTNAME-$$(hostname -i).log

x-cakeshop-def:
  &cakeshop-def
  image: quorumengineering/cakeshop:${QUORUM_CAKESHOP_VERSION:-latest}
  expose:
    - 8999
  restart: "no"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy=off", "http://localhost:8999/actuator/health"]
    interval: 5s
    timeout: 5s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      rm -rf /qdata/cakeshop/local
      mkdir -p /qdata/cakeshop/local
      cp /quorum/application.properties /qdata/cakeshop/local/application.properties

      cp /quorum/8nodes_quorum_docker.json /qdata/cakeshop/local/cakeshop.json

      java -Xms128M -Xmx128M -Dspring.config.additional-location=file:/qdata/cakeshop/local/ -Dcakeshop.config.dir=/qdata/cakeshop -jar /cakeshop/cakeshop.war
      ;;

x-splunk-def:
  &splunk-def
  image: splunk/splunk:8.2
  container_name: splunk
  environment:
    - SPLUNK_START_ARGS=--accept-license
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_PASSWORD=quickstart
    - SPLUNK_APPS_URL=https://github.com/splunkdlt/splunk-app-quorum/releases/download/1.0.7/splunk-app-quorum-v1.0.7.tgz
  ports:
    - 8000:8000
    - 8088:8088
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:8000']
    interval: 5s
    timeout: 5s
    retries: 20
  volumes:
    - ./splunk/splunk.yml:/tmp/defaults/default.yml
    - splunk:/opt/splunk/var

x-otelcollector-def:
  &otelcollector-def
  image: quay.io/signalfx/splunk-otel-collector:0.46.0
  container_name: otelcollector
  depends_on:
    - splunk
  command:
    - --config
    - /etc/otel/config.yaml
  volumes:
    - ./splunk/otel-collector-config.yml:/etc/otel/config.yaml
    - /var/log:/var/log
  environment:
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_ACCESS_TOKEN=disable # You can use this option to send data to Splunk Cloud.
    - SPLUNK_REALM=disable # You can use this option to send data to Splunk Cloud.

x-ethlogger-def:
  &ethlogger-def
  image: ghcr.io/splunkdlt/ethlogger:3.0.1
  container_name: ethlogger
  environment:
    - COLLECT_PEER_INFO=true
    - COLLECT_PENDING_TX=true
    - ETH_RPC_URL=http://rpcnode:8545
    - NETWORK_NAME=quickstart
    - START_AT_BLOCK=latest
    - SPLUNK_HEC_URL=https://splunk:8088
    - SPLUNK_HEC_TOKEN=11111111-1111-1111-1111-1111111111113
    - SPLUNK_EVENTS_INDEX=ledger
    - SPLUNK_METRICS_INDEX=metrics
    - SPLUNK_INTERNAL_INDEX=metrics
    - SPLUNK_HEC_REJECT_INVALID_CERTS=false
    - ABI_DIR=/app/abis
    - DEBUG=ethlogger:platforms,ethlogger:eth
  volumes:
    - ethlogger:/app
    - ./smart_contracts/contracts:/app/abis
  depends_on:
    - splunk
  restart: unless-stopped

x-docker-logging:
  &docker-logging
  logging:
    driver: "splunk"
    options:
      splunk-token: "11111111-1111-1111-1111-1111111111113"
      splunk-url: "https://localhost:8088"
      splunk-index: "logs"
      splunk-insecureskipverify: "true"
      splunk-verify-connection: "false"
      splunk-format: "json"
      tag: "{{.Name}}-{{.ID}}"
      splunk-sourcetype: "docker:logging"
      splunk-source: quorum-quickstart

x-ethsignerProxy-def:
  &ethsignerProxy-def
  image: consensys/quorum-ethsigner:${ETHSIGNER_VERSION:-latest}
  command: [
      "--chain-id=1337",
      "--http-listen-host=0.0.0.0",
      "--downstream-http-port=8545",
      "--downstream-http-host=rpcnode",
      "file-based-signer",
      "-k",
      "/opt/ethsigner/keyfile",
      "-p",
      "/opt/ethsigner/passwordfile"
  ]
  ports:
    - 8545

services:

  validator1:
    << : *besu-bootnode-def
    container_name: validator1
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/tmp/
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.11

  validator2:
    << : *besu-def
    container_name: validator2
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.12

  validator3:
    << : *quorum-def
    container_name: validator3
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=1
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator3:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.13

  validator4:
    << : *quorum-def
    container_name: validator4
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - NODE_ID=2
      - PRIVATE_CONFIG=ignore
    volumes:
      - ./config/goquorum:/quorum
      - ./config/nodes/validator4:/config/keys
      - ./logs/quorum:/var/log/quorum/
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.14

  rpcnode:
    << : *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - public-keys:/opt/besu/public-keys/
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.39

  ethsignerProxy:
    << : *ethsignerProxy-def
    volumes:
      - ./config/ethsigner/password:/opt/ethsigner/passwordfile
      - ./config/ethsigner/key:/opt/ethsigner/keyfile
    depends_on:
      - validator1
      - rpcnode
    ports:
      - 18545:8545/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.104

  cakeshop:
    << : *cakeshop-def
    hostname: cakeshop
    ports:
      - "8999:8999"
    volumes:
      - cakeshop:/data
      - ./config/cakeshop:/quorum
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.100

  explorer:
    build: block-explorer-light/.
    image: quorum-dev-quickstart/block-explorer-light:develop
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.101

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.32

  splunk:
    << : *splunk-def
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.34

  otelcollector:
    << : *otelcollector-def
    << : *docker-logging
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.35

  ethlogger:
    << : *ethlogger-def
    << : *docker-logging
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.36

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --docker_only=true
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.16.239.102

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  cakeshop:
  splunk:
  ethlogger:
  prometheus:
  grafana:
  public-keys:
